- hosts: docker
  vars:
    ansible_ssh_user: root
  tasks:
    - name: Install etc
      apt: name={{ item }} update_cache=yes cache_valid_time=3600
      vars:
        item:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Install gnupg
      apt: name=gnupg update_cache=yes cache_valid_time=3600

    - name: Add key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
#        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
#        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: docker

    - name: Install docker-ce
      apt: name=docker-ce update_cache=yes cache_valid_time=3600

    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: +x
      become: yes
